name: 云编译

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
sudo -E apt-get update
 -E curl -s https://raw.githubusercontent.com/torch/ezinstall/master/install-deps | bash
 -E git clone https://github.com/torch/distro.git ~/torch --recursive
 ./torch; ./install.sh
 -E apt-get install libprotobuf-dev protobuf-compiler
 -E luarocks install loadcaffe
 ./neural-style
 -E sh models/download_models.sh
 -E th neural_style.lua -gpu -1 -print_iter 1
 -E th neural_style.lua -style_image the_scream.jpg -content_image in.jpg -gpu -1

 find ./inputs-name "*combined*jpg*" | xargs -i mv -f {} 
                - name: Upload artifact

        uses: actions/upload-artifact@master

        with:

          name: OpenWrt firmware

          path: ./artifact/
