name: 云编译

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
sudo -E apt-get update
sudo -E curl -s https://raw.githubusercontent.com/torch/ezinstall/master/install-deps | bash
sudo -E git clone https://github.com/torch/distro.git ~/torch --recursive
cd ~/torch; ./install.sh
sudo -E apt-get install libprotobuf-dev protobuf-compiler
输入指令安装loadcaffe：
sudo -E luarocks install loadcaffe
同步源码https://github.com/jcjohnson/neural-style.git
cd neural-style
sh models/download_models.sh
th neural_style.lua -gpu -1 -print_iter 1
th neural_style.lua -style_image the_scream.jpg -content_image in.jpg -gpu -1
#命令解释：th neural_style.lua -style_image风格图片-content_image想处理的图片-gpu -1
